// <auto-generated />
using System;
using APIPEGAWAI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIPEGAWAI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIPEGAWAI.Models.Cabang", b =>
                {
                    b.Property<string>("KodeCabang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NamaCabang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KodeCabang");

                    b.ToTable("Cabangs");
                });

            modelBuilder.Entity("APIPEGAWAI.Models.Jabatan", b =>
                {
                    b.Property<string>("KodeJabatan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NamaJabatan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KodeJabatan");

                    b.ToTable("Jabatans");
                });

            modelBuilder.Entity("APIPEGAWAI.Models.Pegawai", b =>
                {
                    b.Property<string>("KodePegawai")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KodeCabang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KodeJabatan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NamaPegawai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalHabisKontrak")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TanggalMulaiKontrak")
                        .HasColumnType("datetime2");

                    b.HasKey("KodePegawai");

                    b.HasIndex("KodeCabang");

                    b.HasIndex("KodeJabatan");

                    b.ToTable("Pegawais");
                });

            modelBuilder.Entity("APIPEGAWAI.Models.Pegawai", b =>
                {
                    b.HasOne("APIPEGAWAI.Models.Cabang", "Cabang")
                        .WithMany("Pegawais")
                        .HasForeignKey("KodeCabang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIPEGAWAI.Models.Jabatan", "Jabatan")
                        .WithMany("Pegawais")
                        .HasForeignKey("KodeJabatan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cabang");

                    b.Navigation("Jabatan");
                });

            modelBuilder.Entity("APIPEGAWAI.Models.Cabang", b =>
                {
                    b.Navigation("Pegawais");
                });

            modelBuilder.Entity("APIPEGAWAI.Models.Jabatan", b =>
                {
                    b.Navigation("Pegawais");
                });
#pragma warning restore 612, 618
        }
    }
}
